### ISSUE TITLE
Plugin Error (Qtv5.10, VS2017)

### ISSUE THREAD

**Issue by Guru-Soft** [jesperhh/teamfoundation#10]
Instructions followed but got these issues:

Could not resolve dependency 'Core(4.3.0)'
Could not resolve dependency 'VcsBase(4.3.0)'

**Comment by jesperhh** [comment]
I have released an updated version of the plugin, could you try it out?

**Comment by Guru-Soft** [comment]
Thanks a lot, it was quick! and works for me
